site_name: I-analyzer Readers
repo_url: https://github.com/UUDigitalHumanitieslab/ianalyzer-readers
plugins:
  - mkdocstrings
nav:
  - 'index.md'
  - 'api.md'
  - 'examples.md'
watch:
  - docs
  - ianalyzer_readers